blank_issues_enabled: false
contact_links:
  - name: ðŸ“š Documentation
    url: https://railgunlabs.com/unicorn/manual
    about: Review documentation and code examples.
  - name: ðŸ”¹ Basic Support
    url: https://railgunlabs.com/contribute
    about: Submit unsolicited bugs reports and code contributions.
  - name: ðŸ’Ž Premium Support
    url: https://railgunlabs.com/services
    about: Priority support for bug reports and personal Q&A assistance.
